### ISSUE TITLE
Enable Code Cov Report

### ISSUE THREAD

**Issue by chrispenny** [silverstripe-terraformers/keys-for-cache#4]
Using the following config:
```yaml
jobs:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_COVERAGE_TEST=1
```

Results in the following error:
![Screen Shot 2021-08-26 at 10 45 57 AM](https://user-images.githubusercontent.com/505788/130880943-067e8e5a-c078-44f7-a424-9256ce3f67e7.png)

https://app.travis-ci.com/github/silverstripe-terraformers/keys-for-cache/builds/236239654
